### ISSUE TITLE
Possible indentation bug

### ISSUE THREAD

**Issue by wetisobe** [nbaertsch/nimvoke#1]
I just pulled the current project in one of my build-pipelines and they are not working for x64 anymore. The error reads:
```
/root/.nimble/pkgs2/nimvoke-1.0.0-618ae315d48f2977de69535f404bcffda0563de1/nimvoke/inc/common.nim(56, 1) Error: redefinition of 'GetPEB'; 
previous declaration here: /root/.nimble/pkgs2/nimvoke-1.0.0-618ae315d48f2977de69535f404bcffda0563de1/nimvoke/inc/common.nim(40, 10)
```

I think the error lies in one block that should be indented one more time (starting in L56):
https://github.com/nbaertsch/nimvoke/blob/e9209e5803d474f65f12cb40980b3abac157584c/src/nimvoke/inc/common.nim#L54-L67

This only breaks x64 builds, as it is then defined twice.
Could you please fix it?

Thanks a lot.

**Comment by nbaertsch** [comment]
Sorry, will fix today. Was trying to get x86 working quickly.

**Comment by nbaertsch** [comment]
Should be fixed  - lmk if your still running into issues w/ x64
